config/routes.rb
Snorkel::Application.routes.draw do

  resources :users
  resources :sessions, only: [ :new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  match "/signup", to: "users#new", via: 'get'
  match "/logins", to: 
    "logins#index", via:'get'
  root 'static_pages#home'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/signup', to: 'users#new', via: 'get'
  get "static_pages/help"
  get "static_pages/about"

     resources :users do
       member do
         get :following, :followers
       end
      end

  

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', 
      collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%=feed_item.id%>">
<%= link_to gravatar_for(feed_item.user),feed_item.user %>
<span class="user">
  <%= link_to feed_item.user.username, feed_item.user %>
</span>
<span class="content">
  <%= wrap(feed_item.content) %>
</span>
<span class="timestamp">
  Posted <%= time_ago_in_words(feed_item.created_at)%> ago.
</span>
<% if current_user?(feed_item.user) %>
  <%= link_to "delete", feed_item, method: :delete,
    data: { confirm: "You sure?" },  
    title: feed_item.content %>
<% end %>
</li>

app/views/shared/_flashed.html.erb
<% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>

app/views/shared/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Snorkel", root_path, id: "logo" %>
      <nav>
        <%= render 'shared/menu' %>
      </nav>
    </div>
  </div>
</header>

app/views/shared/_login_item.html.erb
<li>
  <%= gravatar_for(login_item.user, { size:15 }) %>
  <%=link_to login_item.user.username, login_item.user %>
    <%=" has been logged in for #{time_ago_in_words(last_login)}" %>
    <%= " and has logged in #{ pluralize(login_item.user.logins.count, 'time')}" %>
</li>

app/views/shared/_menu.html.erb
<nav>
  <ul class="nav pull-left">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Help", help_path %></li>
    <li><%=link_to "Online", logins_path  %></li>
    <% if signed_in? %>
      <li><%= link_to "Users", users_path %></li>
      <li id="fat-menu" class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Account <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "Sign out", signout_path, method: "delete" %>
          </li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to "Sign in", signin_path %></li>
    <% end %>
  </ul>
</nav>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..."
      %>
          <p class="help-inline"><span class="counter"></span>
    
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>
<script type="text/javascript">
		//default usage
		//custom usage
		$("#micropost_content").charCount({
			allowed: 140,		
			warning: 20,
			counterText: 'Characters left: '	
		});
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
  <strong id="following" class="stat">
    <%= @user.followed_users.count %>
  </strong>
  following
  </a>
  <a href=<%=followers_user_path(@user)%>>
    <strong id="followers" class="stat">
      <%=  @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<!--Message.all.group_by { |m| m.created_at.beginning_of_month } ->
<%= link_to gravatar_for(current_user, size:52), current_user %>
<h3>
  <%= current_user.name %>
</h3>
<span>
  <%= link_to "View my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>
<!-- -->
<!-- -->

app/views/shared/_user_not_signed_in.html.erb
<div class='center hero-unit'>
  <h1>Snorkel Home</h1>
  <% if current_user %>
  <%= link_to "Already have a snorkel?", 
    current_user, class: "btn btn-large btn-primary"%>
  <% else current_user%>
    <%= link_to "Start Sorkeling", signup_path, 
      class: "btn btn-large btn-primary"%>
  <%end%>
</div>

app/views/shared/_user_signed_in.html.erb
<div class="row ">
  <aside class="span4">
    <section>
      <%= render 'shared/user_info' %>
    </section>
    <section>
    <%=render 'shared/stats' %>
    </section>
    <section>
    <%= render 'shared/micropost_form' %>
    </section>
    <section>
    <%= link_to "see who's logged in", logins_path %>
    </section>
  </aside>
  <div class="span8 pull-right">
    <h6 class="feed">Snorks</h6>
      <%= render 'shared/feed' %>
  </div>
</div>